spring:
  application:
    name: CaseManagementSystem
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/case_management
    username: postgres
    password: Admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  # Flowable Configuration
  flowable:
    database-schema-update: true
    async-executor-activate: true
    history-level: audit

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /cms

# Logging Configuration
logging:
  level:
    com.example.casemanagementsystem: DEBUG
    org.flowable: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application specific configuration
cms:
  case:
    id-prefix: "CASE-"
  task:
    id-prefix: "TASK-"
  queue:
    investigations: "Investigations"
